Egyptian-Financial-Advisor:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: de-practice-490214
      dataset: efa_main
      threads: 4
      keyfile: /app/Egyptian-Financial-Advisor/gcp-key.json 
      timeout_seconds: 300
      priority: interactive